## Tensor

### Initializing a tensor

In [5]:
import torch
import numpy as np

data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

shape =(2,3)
rand_tensor = torch.rand(shape)
ones_tensor =torch.ones(shape)
zeros_tensor= torch.zeros(shape)
print(rand_tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[0.9754, 0.6291],
        [0.0207, 0.9325]])
tensor([[0.9859, 0.3070, 0.8260],
        [0.4130, 0.4827, 0.0803]])


### Attributes of a Tensor

In [7]:
tensor = torch.rand(3,4)
print("Shape of tensor: {}".format(tensor.shape))
print("Datatype of tensor: {}".format(tensor.dtype))
print("Device tensor is stored on: {}".format(tensor.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Device

In [9]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
    print("cuda is not available!")
print("Device tensor is stored on: {}".format(tensor.device))

device = 0
if torch.cuda.is_available():
    tensor = tensor.to('cuda:{}'.format(device))
print("Device tensor is stored on: {}".format(tensor.device))

tensor = tensor.cpu()
# tensor = tensor.to('cpu')
print("Device tensor is stored on: {}".format(tensor.device))


Device tensor is stored on: cuda:0
Device tensor is stored on: cuda:0
Device tensor is stored on: cpu


### Indexing, slicing and joining tensors

In [14]:
l = list(range(9))
tensor =torch.tensor(l).reshape((3,3))
print("Original 3*3 tenstor:")
print(tensor)

print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[...,-1])

t1= torch.cat([tensor, tensor], dim=1)
t2 = torch.stack([tensor,tensor] , dim=1)

print("\nAfter concat:")
print(t1)
print("\nAfter stack:")
print(t2)

Original 3*3 tenstor:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
First row:  tensor([0, 1, 2])
First column:  tensor([0, 3, 6])
Last column:  tensor([2, 5, 8])

After concat:
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])

After stack:
tensor([[[0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5]],

        [[6, 7, 8],
         [6, 7, 8]]])


### Arithmetic operations

In [17]:
# the matrix multiplication
y1 = tensor @ tensor.T
y2= tensor.matmul(tensor.T)
y3 = torch.matmul(tensor,tensor.T)
print('-'*20)
print(y1)
print(y2)
print(y3)

# the element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.mul(tensor,tensor)
print('-'*20)
print(z1)
print(z2)
print(z3)

# in-place operations
i1 = tensor.add(5)
i2 = tensor.mul(5)
print('-'*20)
print(i1)
print(i1)


--------------------
tensor([[  5,  14,  23],
        [ 14,  50,  86],
        [ 23,  86, 149]])
tensor([[  5,  14,  23],
        [ 14,  50,  86],
        [ 23,  86, 149]])
tensor([[  5,  14,  23],
        [ 14,  50,  86],
        [ 23,  86, 149]])
--------------------
tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])
tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])
tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])
--------------------
tensor([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]])


# Trainign a CNN Network

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

## Dataset

### Loading train set and test set

In [ ]:

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
 
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=0)
 
testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=0)
 
classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
 
def imshow(img):
    img = img / 2 + 0.5  # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg,(1, 2, 0)))
    plt.show()


# get some random training images
dataiter = iter(trainloader)
images, labels = dataiter.next()
 
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join('%5s' % classes[labels[j]] for j in range(4)))


## Neural Network

###  Module

In [ ]:
class CNN(nn.Module):
 
    def __init__(self):
        super(CNN,self).__init__()
        self.conv1 = nn.Conv2d(3,64,3,padding=1)
        self.conv2 = nn.Conv2d(64,64,3,padding=1)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu1 = nn.ReLU()
 
        self.conv3 = nn.Conv2d(64,128,3,padding=1)
        self.conv4 = nn.Conv2d(128, 128, 3,padding=1)
        self.pool2 = nn.MaxPool2d(2, 2, padding=1)
        self.bn2 = nn.BatchNorm2d(128)
        self.relu2 = nn.ReLU()
 
        self.conv5 = nn.Conv2d(128,128, 3,padding=1)
        self.conv6 = nn.Conv2d(128, 128, 3,padding=1)
        self.conv7 = nn.Conv2d(128, 128, 1,padding=1)
        self.pool3 = nn.MaxPool2d(2, 2, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.relu3 = nn.ReLU()
 
        self.conv8 = nn.Conv2d(128, 256, 3,padding=1)
        self.conv9 = nn.Conv2d(256, 256, 3, padding=1)
        self.conv10 = nn.Conv2d(256, 256, 1, padding=1)
        self.pool4 = nn.MaxPool2d(2, 2, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.relu4 = nn.ReLU()
 
        self.conv11 = nn.Conv2d(256, 512, 3, padding=1)
        self.conv12 = nn.Conv2d(512, 512, 3, padding=1)
        self.conv13 = nn.Conv2d(512, 512, 1, padding=1)
        self.pool5 = nn.MaxPool2d(2, 2, padding=1)
        self.bn5 = nn.BatchNorm2d(512)
        self.relu5 = nn.ReLU()
 
        self.fc14 = nn.Linear(512*4*4,1024)
        self.drop1 = nn.Dropout2d()
        self.fc15 = nn.Linear(1024,1024)
        self.drop2 = nn.Dropout2d()
        self.fc16 = nn.Linear(1024,10)
 
 
    def forward(self,x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.pool1(x)
        x = self.bn1(x)
        x = self.relu1(x)
 
 
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.pool2(x)
        x = self.bn2(x)
        x = self.relu2(x)
 
        x = self.conv5(x)
        x = self.conv6(x)
        x = self.conv7(x)
        x = self.pool3(x)
        x = self.bn3(x)
        x = self.relu3(x)
 
        x = self.conv8(x)
        x = self.conv9(x)
        x = self.conv10(x)
        x = self.pool4(x)
        x = self.bn4(x)
        x = self.relu4(x)
 
        x = self.conv11(x)
        x = self.conv12(x)
        x = self.conv13(x)
        x = self.pool5(x)
        x = self.bn5(x)
        x = self.relu5(x)
        # print(" x shape ",x.size())
        x = x.view(-1,512*4*4)
        x = F.relu(self.fc14(x))
        x = self.drop1(x)
        x = F.relu(self.fc15(x))
        x = self.drop2(x)
        x = self.fc16(x)
 
        return x

### test_kwargs

In [19]:
def test_kwargs(first, *args, **kwargs):
    print('Required argument:', first)
    print(type(args))
    print(type(kwargs))
    print('-'*24)
    for v in args:print('0ptional argument(args): ', v)
    print('-'*24)
    for k,v in kwargs.items():
        print('0ptional argument %s(kwargs):%s'%(k, v))
                                                 
test_kwargs(1,2,3,4,k1=5,k2=6)

Required argument: 1
<class 'tuple'>
<class 'dict'>
------------------------
0ptional argument(args):  2
0ptional argument(args):  3
0ptional argument(args):  4
------------------------
0ptional argument k1(kwargs):5
0ptional argument k2(kwargs):6


In [ ]:
model = CNN()
for name, param in resnet18.named_parameters():
    print(name, param.size())

### load pretrained models

In [21]:
import torchvision.models as models
resnet18 = models.resnet18(pretrained=True)

/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/ubuntu/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:01<00:00, 24.4MB/s]


In [ ]:
### Parameters

### Loss function and optimizer

In [ ]:
loss = nn.CrossEntropyLoss()
#optimizer = optim.SGD(self.parameters(),lr=0.01)
optimizer = optim.Adam(model.parameters(), lr=0.0001)

In [ ]:
device = 'cpu' # switch to cuda if cuda is avaliable

for epoch in range(10):  # loop over the dataset multiple times
    timestart = time.time()

    running_loss = 0.0
    total = 0
    correct = 0
    for i, data in enumerate(trainloader, 0):
        # get the inputs
        inputs, labels = data
        inputs, labels = inputs.to(device),labels.to(device)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = self(inputs)
        l = loss(outputs, labels)
        l.backward()
        optimizer.step()

        # print statistics
        running_loss += l.item()
        # print("i ",i)
        if i % 500 == 499:  # print every 500 mini-batches
            print('[%d, %5d] loss: %.4f' %
                    (epoch, i, running_loss / 500))
            running_loss = 0.0
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            print('Accuracy of the network on the %d tran images: %.3f %%' % (total,
                    100.0 * correct / total))
            total = 0
            correct = 0

    print('epoch %d cost %3f sec' %(epoch,time.time()-timestart))
 
print('Finished Training')

## Save and load models

### Save model

In [ ]:
path = ".weight/CNN_model.tar"
torch.save({'epoch':epoch,
            'model_state_dict':model.state_dict(),
            'optimizer_state_dict':optimizer.state_dict(),
            'loss':loss
            },path)

### load model and Test
checkpoint = torch.load(path)
model.load_state_dict(checkpoint['model_state_dict'])

In [ ]:
def test(self,device):
    correct = 0
    total = 0
    with torch.no_grad():
        for data in testloader:
            images, labels = data
            images, labels = images.to(device), labels.to(device)
            outputs = self(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the 10000 test images: %.3f %%' % (
                100.0 * correct / total))